---
engines:
 rubocop:
   enabled: true

pylint:
  enabled: true
  python_version: 3

exclude_paths:
  - '.github/**'
  - '**.md'
  - 'docs/**'
  - 'paper/**'
  - DNetPRO/__init__.py
  - DNetPRO/test/*
  - toy/**
  - timing/**
