# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - cmake
    - doxygen
  jobs:
    install:
      - python -m pip install --upgrade pip
      - python -m pip install -r requirements.txt
      - python -m pip install -r docs/requirements.txt
      - python -m pip install cython numpy sphinx sphinx-rtd-theme breathe nbsphinx ipython
    build:
      html:
        - cmake -S . -B build -DBUILD_DOCS=ON -DSKBUILD=ON
        - cmake --build build --target py_docs
        - mkdir --parents "$READTHEDOCS_OUTPUT/html"
        - cp --recursive docs/build/* "$READTHEDOCS_OUTPUT/html/"
