name: DNetPRO-dev
channels:
  - default
  - anaconda
  - conda-forge

dependencies:
  # error: numpy 1.23.1 is installed but numpy<1.23.0,>=1.16.5 is required by {'scipy'}
  - numpy<1.23.0,>=1.16.5
  # required
  - cython>=0.29
  - networkx>=2.2
  - scikit-learn>=0.20.3
  - pandas>=0.24.2

  # building
  - pkgconfig
  - cython>=0.29
  - cmake
  - doxygen

  # documentation
  - breathe>=4.14.1
  - nbsphinx
  - IPython
