name: DNetPRO-dev
channels:
  - default
  - anaconda
  - conda-forge

dependencies:
  # error: numpy 1.23.1 is installed but numpy<1.23.0,>=1.16.5 is required by {'scipy'}
  - numpy>=1.16
  - networkx>=2.2
  - scikit-learn>=0.19.1
  - pandas>=0.24.2

  # building
  - pkgconfig
  - scikit-build>=0.13
  - Cython
  - cmake
  - doxygen
  - ninja

  # documentation
  - breathe>=4.14.1
  - nbsphinx
  - IPython
