find_program(CYTHON_EXECUTABLE NAMES cython cython3)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Cython REQUIRED_VARS CYTHON_EXECUTABLE)

mark_as_advanced(CYTHON_EXECUTABLE)